version: '3.8'

services:
  app:
    build: .
    ports:
      - '5000:5000'
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: example
      DB_NAME: ecommerce
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: ecommerce
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
